version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: authsystem-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authsystem
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: authsystem-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
